name: Multiarch-build

on:
  push:
  pull_request:

jobs:
  multiarch-build:
    uses: npastorale/workflows/.github/workflows/multiarch-build.yaml@main
    permissions:
      contents: read
      packages: write
    with:
      username: npastorale
      image: web
      package: web
    secrets:
      access-token: ${{ secrets.docker_token }}
